services:
  # stacks-blockchain standalone instance
  - name: mocknet-stacks-blockchain
    type: web
    env: docker
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: mocknet-render 
    dockerfilePath: standalone.Dockerfile
    dockerContext: .
    # dockerCommand: /start
    healthCheckPath: /status
    envVars:
      - key: PG_HOST
        fromService:
          name: mocknet-postgres
          type: pserv
          property: host
      - key: PG_PORT
        value: 5432
      - key: PG_USER
        value: postgres
      - key: PG_PASSWORD
        fromService:
          type: pserv
          name: mocknet-postgres
          envVarKey: POSTGRES_PASSWORD
      - key: PG_DATABASE
        value: postgres
      - key: STACKS_CORE_EVENT_PORT
        value: 3700
      - key: STACKS_CORE_EVENT_HOST
        value: 0.0.0.0
      - key: STACKS_BLOCKCHAIN_API_PORT
        value: 3999
      - key: STACKS_BLOCKCHAIN_API_HOST
        value: 0.0.0.0
      - key: STACKS_BLOCKCHAIN_API_DB
        value: pg
      - key: STACKS_CORE_RPC_HOST
        value: localhost
        # fromService:
        #   name: mocknet-stacks-blockchain
        #   type: pserv
        #   property: host
      - key: STACKS_CORE_RPC_PORT
        value: 20443
      - fromGroup: mocknet-settings

  # Private Postgres instance
  - name: mocknet-postgres
    type: pserv
    env: docker
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: mocknet-render
    dockerfilePath: postgres.Dockerfile
    envVars:
      - key: POSTGRES_PASSWORD
        generateValue: true # will generate a base64-encoded 256-bit secret


envVarGroups:
  - name: mocknet-settings
    envVars:
      - key: NODE_ENV
        value: production
      - key: GIT_TAG
        value: master
      - key: STACKS_CHAIN_ID
        value: 2147483648
      - key: V2_POX_MIN_AMOUNT_USTX
        value: 90000000260
      - key: STACKS_NETWORK
        value: mocknet
      # - key: STACKS_EXPORT_EVENTS_FILE
      #   value: /tmp/event-replay/stacks-node-events.tsv
      # - key: BNS_IMPORT_DIR
      #   value: /bns-data

 
