services:
  - name: mainnet-stacks-blockchain
    type: web
    env: docker
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: mainnet-render
    dockerfilePath: standalone.Dockerfile
    dockerContext: .
    healthCheckPath: /status
    envVars:
      - key: PG_HOST
        fromDatabase:
          name: mainnet-postgres
          property: host
      - key: PG_PORT
        fromDatabase:
          name: mainnet-postgres
          property: port
      - key: PG_DATABASE
        fromDatabase:
          name: mainnet-postgres
          property: database
      - key: PG_USER
        fromDatabase:
          name: mainnet-postgres
          property: user
      - key: PG_PASSWORD
        fromDatabase:
          name: mainnet-postgres
          property: password
      - key: STACKS_CORE_EVENT_PORT
        value: 3700
      - key: STACKS_CORE_EVENT_HOST
        value: 0.0.0.0
      - key: STACKS_BLOCKCHAIN_API_PORT
        value: 3999
      - key: STACKS_BLOCKCHAIN_API_HOST
        value: 0.0.0.0
      - key: STACKS_BLOCKCHAIN_API_DB
        value: pg
      - key: STACKS_CORE_RPC_HOST
        value: localhost
      - key: STACKS_CORE_RPC_PORT
        value: 20443
      - fromGroup: mainnet-settings
    disk:
      name: stacks-blockchain-data
      mountPath: /root/stacks-blockchain/data
      sizeGB: 50 # optional
    databases:
      - name: mainnet-postgres
        databaseName: mainnet # optional (Render may add a suffix)
        user: mainnet # optional
        ipAllowList: []

envVarGroups:
  - name: mainnet-settings
    envVars:
      - key: NODE_ENV
        value: production
      - key: GIT_TAG
        value: master
      - key: STACKS_CHAIN_ID
        value: 0x00000001
      - key: V2_POX_MIN_AMOUNT_USTX
        value: 90000000260
      - key: STACKS_NETWORK
        value: mainnet
      - key: STACKS_EXPORT_EVENTS_FILE
        value: /root/stacks-blockchain/stacks-node-events.tsv
